### ISSUE TITLE
Cannot get high acc when use create_ggnn_mp_layers.

### ISSUE THREAD

**Issue by shangqing-liu** [microsoft/ptgnn#20]
Hello,

Thanks for this great repo and I use it to play with varmisuse, but I have some questions about it. In the implementation, it seems that two different layers provided, create_mlp_mp_layers (see https://github.com/microsoft/ptgnn/blob/ef13a9fec027b8bc4a2804153a29f163cc1813d9/ptgnn/implementations/varmisuse/train.py#L42)
and create_ggnn_mp_layers (see
https://github.com/microsoft/ptgnn/blob/ef13a9fec027b8bc4a2804153a29f163cc1813d9/ptgnn/implementations/varmisuse/train.py#L76)
and in GGNN model, it invokes create_mlp_mp_layers (see
https://github.com/microsoft/ptgnn/blob/ef13a9fec027b8bc4a2804153a29f163cc1813d9/ptgnn/implementations/varmisuse/train.py#L114)
to build the model, however according to my understanding, mlp layers are just fully-connected layers without message passing for graph learning, so I replace it with create_ggnn_mp_layers function for learning. But the results are not promising, with only 72.50 test accuracy on the same split from https://github.com/microsoft/ptgnn/issues/1. Furthermore, mlp layers provide much higher accuracy, 81.13 test accuracy. It seems there is something wrong, but I cannot figure it out.

Best wishes.

**Comment by mallamanis** [comment]
Hi @shangqing-liu,

Both the MLP and GGNN message-passing layers are doing message passing. The MLP is *not* just a per-node fully-connected layer. Instead, the difference is how the messages are computed. For the GGNN these are computed as in the GGNN paper with a GRU.  The [`MlpMessagePassingLayer`](https://github.com/microsoft/ptgnn/blob/ef13a9fec027b8bc4a2804153a29f163cc1813d9/ptgnn/neuralmodels/gnn/messagepassing/mlpmessagepassing.py#L12) instead uses an MLP to compute the messages and an MLP to update the node states, which is more powerful/expressive.

So, the results you observe are expected, but you're wrong about what the `create_mlp_mp_layers` does.

Note that the `MlpMessagePassingLayer` (with the residuals) is also what we use in our latest work [here](https://arxiv.org/abs/2105.12787) exactly because it has a better performance compared to GGNNs.

**Comment by shangqing-liu** [comment]
Thanks, I will follow it closely.
